# Push a newly tagged version to the live site.
name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  CI: ""

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18.2'

      - name: Viewer App
        run: cd web/viewer && npm ci && npm run build && cp -r ./build ../../internal/assets/viewer/

      - name: Controller App
        run: cd web/controller && npm ci && npm run build && cp -r ./build ../../internal/assets/controller/

      - name: Build Go Binary
        run: go build -o ./build ./...

      - name: Stop Maze Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOSTNAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: 22
          script: systemctl stop maze

      - name: Push to server
        working-directory: ./
        run: |
          echo "::group::Setup Auth Keys"
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "::endgroup::"
          
          echo "::group::Pre-approve rsync destination"
          ssh-keyscan -H ${{ secrets.DEPLOY_HOSTNAME }} > ~/.ssh/known_hosts
          echo "::endgroup::"

          echo "::group::SCP file"
          scp ./build/maze-game-server ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOSTNAME }}:${{ secrets.DEPLOY_PATH }}
          echo "::endgroup::"

      - name: Start Maze Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOSTNAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: 22
          script: systemctl start maze
